version: '3.3'

services:
  redis:
    container_name: sbs_redis
    image: redis:6.2.3
    ports:
      - 6380:6379

  bot:
    container_name: weather_telegram_bot
    build:
      context: .
    ports:
    - 1994:1994
    depends_on:
      - redis